### PR TITLE
Jdk8u222 b10

### PR DESCRIPTION
**Pull request by MatMaul**

### CODE REVIEW

**Comment by MatMaul** [comment]
bot, build

**Comment by nedrichards** [comment]
Cool! Are we planning on enabling this for 19.08 as well?

**Comment by MatMaul** [comment]
Yep I'll EOL 1.6 and put 19.08.
Regarding branching do you see a problem by removing the master branch, and only keep branch/* ones ?

**Comment by MatMaul** [comment]
@nedrichards can you delete branch `master` and put `branch/19.08` as default, or give me the rights to do so ?
Thanks !

**Pull request merged**
